version: '3.5'

services:
  mongo:
    image: mongo:5
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - '3000:3000'