production:
  clients:
    default:
     uri: <%= ENV['MONGODB_URI'] %>

     options:
       connect_timeout: 15
       retry_writes: true
       max_pool_size: 5
  options:
    raise_not_found_error: false


development:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongo://localhost:27017') %>
      options:
        retry_writes: false
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongo://localhost:27017') %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
        retry_writes: false
  options:
    raise_not_found_error: false